# DO NOT EDIT THIS FILE
#
# Please edit /boot/fnEnv.txt to set supported parameters
#

setenv overlay_error "false"
# default values
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv docker_optimizations "on"
setenv earlycon "off"

if test $soc = 'rk3576'; then
	setenv load_addr "0x48000000"
else
	setenv load_addr "0x9000000"
fi

test -n "${kernelfile}" || kernelfile="vmlinuz"

test -n "${distro_bootpart}" || distro_bootpart=1
test -n "${distro_rootpart}" || distro_rootpart=2

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fnEnv.txt; then
	load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fnEnv.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test $soc = 'rk3308'; then
	serial_addr=',0xff0c0000'; serial_port='ttyS2';
elif test $soc = 'rk3328'; then
	serial_addr=',0xff130000'; serial_port='ttyS2';
elif test $soc = 'rk3399'; then
	serial_addr=',0xff1a0000'; serial_port='ttyS2';
elif test $soc = 'rk3528'; then
	serial_addr=',0xff9f0000'; serial_port='ttyS0';
elif test $soc = 'rk3568'; then
	serial_addr=',0xfe660000'; serial_port='ttyS2';
elif test $soc = 'rk3576'; then
	serial_addr=',0x2ad40000'; serial_port='ttyS0';
elif test $soc = 'rk3588'; then
	serial_addr=',0xfeb50000'; serial_port='ttyS2';
fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=${serial_port},1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from
part uuid ${devtype} ${devnum}:${distro_bootpart} bootuuid
part uuid ${devtype} ${devnum}:${distro_rootpart} rootuuid

setenv bootargs "root=PARTUUID=${rootuuid} rootwait rw ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=PARTUUID=${bootuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test -n "${rootfstype}"; then setenv bootargs "${bootargs} rootfstype=${rootfstype}"; fi

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}${kernelfile}

initrd_load_addr="-"
if test -n "${initrdfile}"; then
	if load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}${initrdfile}; then
		initrd_load_addr="${ramdisk_addr_r}"
	fi
fi

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
if test "${overlay_error}" = "true"; then
	echo "Error applying DT overlays, restoring original DT"
	load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

booti ${kernel_addr_r} ${initrd_load_addr} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
